#!/bin/sh
# External deps setup tool
# This should:
# - identify your dev system (mac os/linux incl. Windows WSL/ssh'd)
# - identify your package manager
# - install neovim from that package manager (if 0.10+?)
# - install all other utilities (e.g ripgrep, jq etc)
# - init.lua no longer checks for utilities, because it can't print to STDOUT and working this into
# lua seems like the wrong place.. but after writing this script maybe it can be transferred we'll
# see!

set +e

mkdir -p $HOME/.notes/src
mkdir -p $HOME/.config/nvim/pack/base/start
mkdir -p $HOME/.config/tmux

# chsh -s /bin/bash

available() {
    which $1 > /dev/null 2>&1
    echo $?
}

join_by() { local IFS="$1"; shift; echo "$*"; }

brew_available=$(available brew)
pacman_available=$(available pacman)
dnf_available=$(available pacman)
apt_available=$(available pacman)

# packages that share the same name between package managers.
# packages to add: node & jdk are named differently.
# only linux requires x11 + wayland clipboard utils to integrate with system clipboard.
common_packages=(
    git
    ripgrep
    htop
    tmux
    postgresql
    wget
    openssh
    go
    rustup
    ruby
    python
    jq
    neovim
)

if [[ $brew_available -eq 0 ]]; then
    echo 'brew found'
    brew install $(join_by ' ' "${common_packages[@]}") node openjdk
elif [[ $pacman_available -eq 0 ]]; then
    echo 'pacman found'
    sudo pacman -Syu --needed $(join_by ' ' "${common_packages[@]}") nodejs jdk-openjdk wl-clipboard xclip
else
    echo 'package manager not found/supported (dnf/apt specifically not supported)'
fi

if [[ $(available go) ]]; then
    if [[ $(available air) -eq 1 ]]; then
        go install github.com/air-verse/air@latest
    fi

    if [[ $(available present) -eq 1 ]]; then
        go install golang.org/x/tools/cmd/present@latest
    fi

    if [[ $(available gopls) -eq 1 ]]; then
        go install golang.org/x/tools/gopls@latest
    fi

    if [[ $(available golangci-lint) -eq 1 ]]; then
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.60.3
    fi
fi
